services:
  - type: web
    name: superspace-server
    runtime: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 10000
    plan: free
